kind: pipeline
type: docker
name: default

steps:
- name: nuxt
  image: node
  environment:
    CLOUDRON_URL:
      from_secret: CLOUDRON_URL
    CLOUDRON_USERNAME:
      from_secret: CLOUDRON_USERNAME
    CLOUDRON_PASSWORD:
      from_secret: CLOUDRON_PASSWORD
    BUILD_URL:
      from_secret: BUILD_URL
    BUILD_TOKEN:
      from_secret: BUILD_TOKEN
  commands:
  - cd atridad
  - ls
  - npm i -g cloudron
  - yarn
  - yarn build

- name: test
  image: docker:dind
  environment:
    DOCKER_USERNAME:
      from_secret: DOCKER_USERNAME
    DOCKER_TOKEN:
      from_secret: DOCKER_TOKEN
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker login --username $DOCKER_USERNAME --password $DOCKER_TOKEN
  - docker build -t atridadl/atridad .
  - docker push atridadl/atridad

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock