kind: pipeline
type: docker
name: default

steps:
- name: nuxt
  image: node
  when:
    branch:
    - main
  commands:
  - cd spa
  - yarn
  - yarn build

- name: docker
  image: docker:dind
  when:
    branch:
    - main
  environment:
    DOCKER_USERNAME:
      from_secret: DOCKER_USERNAME
    DOCKER_TOKEN:
      from_secret: DOCKER_TOKEN
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker login --username $DOCKER_USERNAME --password $DOCKER_TOKEN
  - docker build -t atridadl/atridad .
  - docker push atridadl/atridad

- name: cloudron
  image: node
  when:
    branch:
    - main
  environment:
    CLOUDRON_URL:
      from_secret: CLOUDRON_URL
    CLOUDRON_USERNAME:
      from_secret: CLOUDRON_USERNAME
    CLOUDRON_TOKEN:
      from_secret: CLOUDRON_TOKEN
    DOCKER_IMAGE:
      from_secret: DOCKER_IMAGE
    SITE_URL:
      from_secret: SITE_URL
  commands:
  - npm i -g cloudron
  - cloudron update --server $CLOUDRON_URL --token $CLOUDRON_TOKEN --image $DOCKER_IMAGE --app $SITE_URL --no-backup

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

trigger:
  branch:
  - main